name: heroku_deploy_via_git
inputs:
  api_key:
    required: true
  app_name:
    required: false
    default: HEROKU_APP_NAME
  branch:
    required: false
    default: "${{ github.ref }}"
  force:
    required: false
    default: false
  maintenance_mode:
    required: false
    default: false
  tag:
    required: false
    default: "${{ github.ref }}"
runs:
  using: composite
  steps:
  - shell: bash
    env:
      HEROKU_API_KEY: "${{ inputs.api_key }}"
      BRANCH: "${{ inputs.branch }}"
      TAG: "${{ inputs.tag }}"
      FORCE: "${{ inputs.force }}"
      APP_NAME: "${{ inputs.app_name }}"
      MAINTENANCE_MODE: "${{ inputs.maintenance_mode }}"
    run: |-
      if ${{ env.FORCE }};then force="-f"; fi
      heroku_url="https://heroku:${{ env.API_KEY_NAME }}@git.heroku.com/${{ env.APP_NAME }}.git"

      if ${{ env.MAINTENANCE_MODE }}; then heroku maintenance:on --app ${{ env.APP_NAME }}; fi
      if [ -n "${{ env.BRANCH }}" ]; then
        git push $force $heroku_url ${{ env.BRANCH }}:main
      elif [ -n "${{ env.TAG }}" ]; then
        git push $force $heroku_url ${{ env.TAG }}^{}:main
      else
        echo "No branch or tag found."
      fi
      if ${{ env.MAINTENANCE_MODE }}; then heroku maintenance:off --app ${{ env.APP_NAME }}; fi
